### ISSUE TITLE
'Copied' text stays on the screen instead of changing back to 'Copy' button

### ISSUE THREAD

**Issue by Blackbaud-ValKuppuswamy** [blackbaud/skyux-lib-clipboard#14]
We have sky-copy-to-clipboard implemented in one of our SPAs and it used to behave the following way: 1) Click 'Copy' button 2) 'Copied' text will appear on the screen and it will change back to 'Copy' button. In the 1.1.0 version of skyux-lib-clipboard package, the text appears to stay on the screen. Also, if you have more than one copy button on a page, clicking on another copy button seems to close the 'Copied' text. 

![Copy_To_Clipboard](https://user-images.githubusercontent.com/13441187/58573568-082e9600-820c-11e9-8d93-6826c888e5bf.PNG)

**Comment by Blackbaud-LindseyRix** [comment]
Do you have a link (or even a PR link) that we could use to see this happen?

**Comment by Blackbaud-ValKuppuswamy** [comment]
Link to our Supportal SPA: https://host.nxt.blackbaud.com/skydev-supportal/applications/34a57ca8-fe62-40ed-8b1a-ade9bf735a05

**Comment by Blackbaud-TimPepper** [comment]
Resolved by: https://github.com/blackbaud/skyux-lib-clipboard/pull/15

**Comment by Blackbaud-BrandonJones** [comment]
Release `1.1.1` contains the fix that https://github.com/blackbaud/skyux-lib-clipboard/pull/15 addresses.
