### ISSUE TITLE
Components with ChangeDetectionStrategy.OnPush do not reset from the Copied state

### ISSUE THREAD

**Issue by Blackbaud-MatthewMiles** [blackbaud/skyux-lib-clipboard#20]
I'm not sure if this is a side effect of the recent fix in #14 but for Angular Components that have ChangeDetectionStrategy.OnPush for changeDetection, the Copied state never resets.

To replicate, I took another sky component with stackblitz already setup, and added clipboard, confirming changeDetection was OnPush, then viewed "Copied!" to not change.

**Comment by Blackbaud-MatthewMiles** [comment]
@Blackbaud-BrandonJones is this intended or considered a bug?

**Comment by Blackbaud-BrandonJones** [comment]
@Blackbaud-MatthewMiles This isn't intended behavior, which component set up did you use to replicate?

**Comment by Blackbaud-BrandonJones** [comment]
Resolved in `1.1.1` https://github.com/blackbaud/skyux-lib-clipboard/pull/15/files

**Comment by Blackbaud-MatthewMiles** [comment]
I was not using the latest version from #14.  This should be closed
